# Generated by Django 4.2.7 on 2026-05-19 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_seed_notification_types'),
        ('accounts', '0037_add_dynamic_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='context_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivery_channel',
            field=models.CharField(blank=True, default='in_app', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='dynamic_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationtype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
